### ISSUE TITLE
GPL v3 license

### ISSUE THREAD

**Issue by hbredin** [sunits/rir_simulator_python#3]
I would like to integrate (part of) `rir_simulator_python` into [`pyannote.audio`](https://github.com/pyannote/pyannote-audio).

`pyannote.audio` is [MIT](https://github.com/pyannote/pyannote-audio/blob/master/LICENSE) while `rir_simular_python` is [GPL v3](https://github.com/sunits/rir_simulator_python/blob/master/LICENSE). I've looked around how to handle this mismatch ([here](https://stackoverflow.com/questions/11819831/including-gpl-external-library-in-mit-code) and [here](https://www.quora.com/If-I-use-GPL-code-will-I-be-able-to-redistribute-it-with-an-MIT-license)) and that seems overly complicated :-) 

One solution would be for me to switch to GPL but then [other dependencies](https://github.com/mravanelli/SincNet) I use would probably become incompatible. 

However, I noticed that [another project of yours](https://github.com/sunits/Reverberated_WSJ_2MIX) is licensed under MIT. Would you consider switching this repo to MIT as well? Or do you prefer to stick with GPL v3?

**Comment by sunits** [comment]
Changed the licence to MIT.

**Comment by hbredin** [comment]
Great! Thanks a lot!
