### ISSUE TITLE
How to support multiple sources?

### ISSUE THREAD

**Issue by duonianyihouls** [sunits/rir_simulator_python#4]
Hello, I want to simulate two move sources inside the room ? What should I do?

**Comment by sunits** [comment]
This tool is designed assuming that the source and microphone positions are fixed. If you are interested in moving sources, you will find a matlab version here: http://homepages.loria.fr/evincent/software/Roomsimove.zip

**Comment by duonianyihouls** [comment]
hello,This link can't open,May have been deleted,
404 Not Found,
The requested URL was not found on this server.

**Comment by sunits** [comment]
Sorry about that. This link should work: 
http://homepages.loria.fr/evincent/software/Roomsimove_1.4.zip

**Comment by duonianyihouls** [comment]
Thank you very much!
